# Build Stage
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Build binary bot từ thư mục cmd/bot
# RUN go build -o bot cmd/bot/main.go
RUN go build -o bot ./cmd/bot
# Run Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/bot .
EXPOSE 8080
CMD ["./bot"]